[package]
name = "nightcycle/package"
description = "A package!"
version = "0.1.0"
authors = [ "CJ Oyer <coyer@nightcycle.us>",]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = [ "Packages", ".vscode",]

[dependencies]
Maid = "nightcycle/maid@1.1.4"
ServiceProxy = "nightcycle/service-proxy@1.0.0"
OcclusionCamera = "nightcycle/occlusion-camera@1.1.0"
